### ISSUE TITLE
minItems, maxItems and RAML's uniqueItems are missing

### ISSUE THREAD

**Issue by deiteris** [advanced-rest-client/api-type-document#26]
`minItems`, `maxItems` and `uniqueItems` aren't displayed in the API Console.

The following RAML reproduces the issue:
```yaml
#%RAML 1.0

title: Example API
version: v1
mediaType:
  - application/json

/example:
  get:
    body:
      type: object
      properties:
        customArray:
          type: array
          minItems: 1
          maxItems: 7
          uniqueItems: true
          items:
            type: string
```

The properties appear correctly in AMF graph under `shacl:minCount`, `shacl:maxCount` and `raml-shapes:uniqueItems`.

I may suggest the following fix https://github.com/deiteris/api-type-document/commit/aa2bc698a88a807bceed26b325147a645265ac16, but I see that `Namespace.js` in `amf-helper-mixin` lacks some properties, so the issue is a bit more complex.

After the fix, the declared array property looks as follows:
![image](https://user-images.githubusercontent.com/6103913/124640559-3fb1a700-de96-11eb-99cf-ed7b88348ee3.png)
