### ISSUE TITLE
Properties of simple array item types are missing

### ISSUE THREAD

**Issue by deiteris** [advanced-rest-client/api-type-document#27]
Found during https://github.com/advanced-rest-client/api-type-document/issues/26.

The same RAML, but the `string` item contains some constraints:
```yaml
#%RAML 1.0

title: Example API
version: v1
mediaType:
  - application/json

/example:
  get:
    body:
      type: object
      properties:
        customArray:
          type: array
          minItems: 1
          maxItems: 7
          uniqueItems: true
          items:
            type: string
            pattern: ^.*?$
            minLength: 0
            maxLength: 20
```

Results in no constraints displayed for the `string` type in the API console.
